version: 0.1

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://nordictimes
      - aws cloudfront create-invalidation --distribution-id E1ZCIZG6G387RO --paths "/*"
  